mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://doh.dns.sb/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://dns.twnic.tw/dns-query
    - tls://8.8.4.4:853
proxies: []
proxy-groups:
  - name: 布吉岛
    type: select
    proxies:
      - 自动选择
      - 故障转移
      - 负载均衡
  - name: 自动选择
    type: url-test
    proxies: []
    url: http://www.gstatic.com/generate_204
    interval: 86400
  - name: 故障转移
    type: fallback
    proxies: []
    url: http://www.gstatic.com/generate_204
    interval: 7200
  - name: "负载均衡"
    type: load-balance
    proxies: []
    url: "https://www.gstatic.com/generate_204"
    interval: 300
rules:
  - DOMAIN,bujidao.cc,DIRECT
  - DOMAIN-SUFFIX,services.googleapis.cn,布吉岛
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,布吉岛
  - DOMAIN,safebrowsing.urlsec.qq.com,DIRECT
  - DOMAIN,safebrowsing.googleapis.com,DIRECT
  - DOMAIN,developer.apple.com,布吉岛
  - DOMAIN-SUFFIX,digicert.com,布吉岛
  - DOMAIN,ocsp.apple.com,布吉岛
  - DOMAIN,ocsp.comodoca.com,布吉岛
  - DOMAIN,ocsp.usertrust.com,布吉岛
  - DOMAIN,ocsp.sectigo.com,布吉岛
  - DOMAIN,ocsp.verisign.net,布吉岛
  - DOMAIN-SUFFIX,apple-dns.net,布吉岛
  - DOMAIN,testflight.apple.com,布吉岛
  - DOMAIN,sandbox.itunes.apple.com,布吉岛
  - DOMAIN,itunes.apple.com,布吉岛
  - DOMAIN-SUFFIX,apps.apple.com,布吉岛
  - DOMAIN-SUFFIX,blobstore.apple.com,布吉岛
  - DOMAIN,cvws.icloud-content.com,布吉岛
  - DOMAIN-SUFFIX,mzstatic.com,DIRECT
  - DOMAIN-SUFFIX,itunes.apple.com,DIRECT
  - DOMAIN-SUFFIX,icloud.com,DIRECT
  - DOMAIN-SUFFIX,icloud-content.com,DIRECT
  - DOMAIN-SUFFIX,me.com,DIRECT
  - DOMAIN-SUFFIX,aaplimg.com,DIRECT
  - DOMAIN-SUFFIX,cdn20.com,DIRECT
  - DOMAIN-SUFFIX,cdn-apple.com,DIRECT
  - DOMAIN-SUFFIX,akadns.net,DIRECT
  - DOMAIN-SUFFIX,akamaiedge.net,DIRECT
  - DOMAIN-SUFFIX,edgekey.net,DIRECT
  - DOMAIN-SUFFIX,mwcloudcdn.com,DIRECT
  - DOMAIN-SUFFIX,mwcname.com,DIRECT
  - DOMAIN-SUFFIX,apple.com,DIRECT
  - DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT
  - DOMAIN-SUFFIX,apple-mapkit.com,DIRECT
  - DOMAIN-SUFFIX,126.com,DIRECT
  - DOMAIN-SUFFIX,126.net,DIRECT
  - DOMAIN-SUFFIX,127.net,DIRECT
  - DOMAIN-SUFFIX,163.com,DIRECT
  - DOMAIN-SUFFIX,360buyimg.com,DIRECT
  - DOMAIN-SUFFIX,36kr.com,DIRECT
  - DOMAIN-SUFFIX,acfun.tv,DIRECT
  - DOMAIN-SUFFIX,air-matters.com,DIRECT
  - DOMAIN-SUFFIX,aixifan.com,DIRECT
  - DOMAIN-KEYWORD,alicdn,DIRECT
  - DOMAIN-KEYWORD,alipay,DIRECT
  - DOMAIN-KEYWORD,taobao,DIRECT
  - DOMAIN-SUFFIX,amap.com,DIRECT
  - DOMAIN-SUFFIX,autonavi.com,DIRECT
  - DOMAIN-KEYWORD,baidu,DIRECT
  - DOMAIN-SUFFIX,bdimg.com,DIRECT
  - DOMAIN-SUFFIX,bdstatic.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
  - DOMAIN-SUFFIX,caiyunapp.com,DIRECT
  - DOMAIN-SUFFIX,clouddn.com,DIRECT
  - DOMAIN-SUFFIX,cnbeta.com,DIRECT
  - DOMAIN-SUFFIX,cnbetacdn.com,DIRECT
  - DOMAIN-SUFFIX,cootekservice.com,DIRECT
  - DOMAIN-SUFFIX,csdn.net,DIRECT
  - DOMAIN-SUFFIX,ctrip.com,DIRECT
  - DOMAIN-SUFFIX,dgtle.com,DIRECT
  - DOMAIN-SUFFIX,dianping.com,DIRECT
  - DOMAIN-SUFFIX,douban.com,DIRECT
  - DOMAIN-SUFFIX,doubanio.com,DIRECT
  - DOMAIN-SUFFIX,duokan.com,DIRECT
  - DOMAIN-SUFFIX,easou.com,DIRECT
  - DOMAIN-SUFFIX,ele.me,DIRECT
  - DOMAIN-SUFFIX,feng.com,DIRECT
  - DOMAIN-SUFFIX,fir.im,DIRECT
  - DOMAIN-SUFFIX,frdic.com,DIRECT
  - DOMAIN-SUFFIX,g-cores.com,DIRECT
  - DOMAIN-SUFFIX,godic.net,DIRECT
  - DOMAIN-SUFFIX,gtimg.com,DIRECT
  - DOMAIN,cdn.hockeyapp.net,DIRECT
  - DOMAIN-SUFFIX,hongxiu.com,DIRECT
  - DOMAIN-SUFFIX,hxcdn.net,DIRECT
  - DOMAIN-SUFFIX,iciba.com,DIRECT
  - DOMAIN-SUFFIX,ifeng.com,DIRECT
  - DOMAIN-SUFFIX,ifengimg.com,DIRECT
  - DOMAIN-SUFFIX,ipip.net,DIRECT
  - DOMAIN-SUFFIX,iqiyi.com,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,jianshu.com,DIRECT
  - DOMAIN-SUFFIX,knewone.com,DIRECT
  - DOMAIN-SUFFIX,le.com,DIRECT
  - DOMAIN-SUFFIX,lecloud.com,DIRECT
  - DOMAIN-SUFFIX,lemicp.com,DIRECT
  - DOMAIN-SUFFIX,licdn.com,DIRECT
  - DOMAIN-SUFFIX,luoo.net,DIRECT
  - DOMAIN-SUFFIX,meituan.com,DIRECT
  - DOMAIN-SUFFIX,meituan.net,DIRECT
  - DOMAIN-SUFFIX,mi.com,DIRECT
  - DOMAIN-SUFFIX,miaopai.com,DIRECT
  - DOMAIN-SUFFIX,microsoft.com,DIRECT
  - DOMAIN-SUFFIX,microsoftonline.com,DIRECT
  - DOMAIN-SUFFIX,miui.com,DIRECT
  - DOMAIN-SUFFIX,miwifi.com,DIRECT
  - DOMAIN-SUFFIX,mob.com,DIRECT
  - DOMAIN-SUFFIX,netease.com,DIRECT
  - DOMAIN-SUFFIX,office.com,DIRECT
  - DOMAIN-SUFFIX,office365.com,DIRECT
  - DOMAIN-KEYWORD,officecdn,DIRECT
  - DOMAIN-SUFFIX,oschina.net,DIRECT
  - DOMAIN-SUFFIX,ppsimg.com,DIRECT
  - DOMAIN-SUFFIX,pstatp.com,DIRECT
  - DOMAIN-SUFFIX,qcloud.com,DIRECT
  - DOMAIN-SUFFIX,qdaily.com,DIRECT
  - DOMAIN-SUFFIX,qdmm.com,DIRECT
  - DOMAIN-SUFFIX,qhimg.com,DIRECT
  - DOMAIN-SUFFIX,qhres.com,DIRECT
  - DOMAIN-SUFFIX,qidian.com,DIRECT
  - DOMAIN-SUFFIX,qihucdn.com,DIRECT
  - DOMAIN-SUFFIX,qiniu.com,DIRECT
  - DOMAIN-SUFFIX,qiniucdn.com,DIRECT
  - DOMAIN-SUFFIX,qiyipic.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,qqurl.com,DIRECT
  - DOMAIN-SUFFIX,rarbg.to,DIRECT
  - DOMAIN-SUFFIX,ruguoapp.com,DIRECT
  - DOMAIN-SUFFIX,segmentfault.com,DIRECT
  - DOMAIN-SUFFIX,sinaapp.com,DIRECT
  - DOMAIN-SUFFIX,smzdm.com,DIRECT
  - DOMAIN-SUFFIX,snapdrop.net,DIRECT
  - DOMAIN-SUFFIX,sogou.com,DIRECT
  - DOMAIN-SUFFIX,sogoucdn.com,DIRECT
  - DOMAIN-SUFFIX,sohu.com,DIRECT
  - DOMAIN-SUFFIX,soku.com,DIRECT
  - DOMAIN-SUFFIX,speedtest.net,DIRECT
  - DOMAIN-SUFFIX,sspai.com,DIRECT
  - DOMAIN-SUFFIX,suning.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,tencent.com,DIRECT
  - DOMAIN-SUFFIX,tenpay.com,DIRECT
  - DOMAIN-SUFFIX,tianyancha.com,DIRECT
  - DOMAIN-SUFFIX,tmall.com,DIRECT
  - DOMAIN-SUFFIX,tudou.com,DIRECT
  - DOMAIN-SUFFIX,umetrip.com,DIRECT
  - DOMAIN-SUFFIX,upaiyun.com,DIRECT
  - DOMAIN-SUFFIX,upyun.com,DIRECT
  - DOMAIN-SUFFIX,veryzhun.com,DIRECT
  - DOMAIN-SUFFIX,weather.com,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,xiami.com,DIRECT
  - DOMAIN-SUFFIX,xiami.net,DIRECT
  - DOMAIN-SUFFIX,xiaomicp.com,DIRECT
  - DOMAIN-SUFFIX,ximalaya.com,DIRECT
  - DOMAIN-SUFFIX,xmcdn.com,DIRECT
  - DOMAIN-SUFFIX,xunlei.com,DIRECT
  - DOMAIN-SUFFIX,yhd.com,DIRECT
  - DOMAIN-SUFFIX,yihaodianimg.com,DIRECT
  - DOMAIN-SUFFIX,yinxiang.com,DIRECT
  - DOMAIN-SUFFIX,ykimg.com,DIRECT
  - DOMAIN-SUFFIX,youdao.com,DIRECT
  - DOMAIN-SUFFIX,youku.com,DIRECT
  - DOMAIN-SUFFIX,zealer.com,DIRECT
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,zhimg.com,DIRECT
  - DOMAIN-SUFFIX,zimuzu.tv,DIRECT
  - DOMAIN-SUFFIX,zoho.com,DIRECT
  - DOMAIN-KEYWORD,amazon,布吉岛
  - DOMAIN-KEYWORD,google,布吉岛
  - DOMAIN-KEYWORD,gmail,布吉岛
  - DOMAIN-KEYWORD,youtube,布吉岛
  - DOMAIN-KEYWORD,facebook,布吉岛
  - DOMAIN-SUFFIX,fb.me,布吉岛
  - DOMAIN-SUFFIX,fbcdn.net,布吉岛
  - DOMAIN-KEYWORD,twitter,布吉岛
  - DOMAIN-KEYWORD,instagram,布吉岛
  - DOMAIN-KEYWORD,dropbox,布吉岛
  - DOMAIN-SUFFIX,twimg.com,布吉岛
  - DOMAIN-KEYWORD,blogspot,布吉岛
  - DOMAIN-SUFFIX,youtu.be,布吉岛
  - DOMAIN-KEYWORD,whatsapp,布吉岛
  - DOMAIN-KEYWORD,admarvel,REJECT
  - DOMAIN-KEYWORD,admaster,REJECT
  - DOMAIN-KEYWORD,adsage,REJECT
  - DOMAIN-KEYWORD,adsmogo,REJECT
  - DOMAIN-KEYWORD,adsrvmedia,REJECT
  - DOMAIN-KEYWORD,adwords,REJECT
  - DOMAIN-KEYWORD,adservice,REJECT
  - DOMAIN-SUFFIX,appsflyer.com,REJECT
  - DOMAIN-KEYWORD,domob,REJECT
  - DOMAIN-SUFFIX,doubleclick.net,REJECT
  - DOMAIN-KEYWORD,duomeng,REJECT
  - DOMAIN-KEYWORD,dwtrack,REJECT
  - DOMAIN-KEYWORD,guanggao,REJECT
  - DOMAIN-KEYWORD,lianmeng,REJECT
  - DOMAIN-SUFFIX,mmstat.com,REJECT
  - DOMAIN-KEYWORD,mopub,REJECT
  - DOMAIN-KEYWORD,omgmta,REJECT
  - DOMAIN-KEYWORD,openx,REJECT
  - DOMAIN-KEYWORD,partnerad,REJECT
  - DOMAIN-KEYWORD,pingfore,REJECT
  - DOMAIN-KEYWORD,supersonicads,REJECT
  - DOMAIN-KEYWORD,uedas,REJECT
  - DOMAIN-KEYWORD,umeng,REJECT
  - DOMAIN-KEYWORD,usage,REJECT
  - DOMAIN-SUFFIX,vungle.com,REJECT
  - DOMAIN-KEYWORD,wlmonitor,REJECT
  - DOMAIN-KEYWORD,zjtoolbar,REJECT
  - DOMAIN-SUFFIX,9to5mac.com,布吉岛
  - DOMAIN-SUFFIX,abpchina.org,布吉岛
  - DOMAIN-SUFFIX,adblockplus.org,布吉岛
  - DOMAIN-SUFFIX,adobe.com,布吉岛
  - DOMAIN-SUFFIX,akamaized.net,布吉岛
  - DOMAIN-SUFFIX,alfredapp.com,布吉岛
  - DOMAIN-SUFFIX,amplitude.com,布吉岛
  - DOMAIN-SUFFIX,ampproject.org,布吉岛
  - DOMAIN-SUFFIX,android.com,布吉岛
  - DOMAIN-SUFFIX,angularjs.org,布吉岛
  - DOMAIN-SUFFIX,aolcdn.com,布吉岛
  - DOMAIN-SUFFIX,apkpure.com,布吉岛
  - DOMAIN-SUFFIX,appledaily.com,布吉岛
  - DOMAIN-SUFFIX,appshopper.com,布吉岛
  - DOMAIN-SUFFIX,appspot.com,布吉岛
  - DOMAIN-SUFFIX,arcgis.com,布吉岛
  - DOMAIN-SUFFIX,archive.org,布吉岛
  - DOMAIN-SUFFIX,armorgames.com,布吉岛
  - DOMAIN-SUFFIX,aspnetcdn.com,布吉岛
  - DOMAIN-SUFFIX,att.com,布吉岛
  - DOMAIN-SUFFIX,awsstatic.com,布吉岛
  - DOMAIN-SUFFIX,azureedge.net,布吉岛
  - DOMAIN-SUFFIX,azurewebsites.net,布吉岛
  - DOMAIN-SUFFIX,bing.com,布吉岛
  - DOMAIN-SUFFIX,bintray.com,布吉岛
  - DOMAIN-SUFFIX,bit.com,布吉岛
  - DOMAIN-SUFFIX,bit.ly,布吉岛
  - DOMAIN-SUFFIX,bitbucket.org,布吉岛
  - DOMAIN-SUFFIX,bjango.com,布吉岛
  - DOMAIN-SUFFIX,bkrtx.com,布吉岛
  - DOMAIN-SUFFIX,blog.com,布吉岛
  - DOMAIN-SUFFIX,blogcdn.com,布吉岛
  - DOMAIN-SUFFIX,blogger.com,布吉岛
  - DOMAIN-SUFFIX,blogsmithmedia.com,布吉岛
  - DOMAIN-SUFFIX,blogspot.com,布吉岛
  - DOMAIN-SUFFIX,blogspot.hk,布吉岛
  - DOMAIN-SUFFIX,bloomberg.com,布吉岛
  - DOMAIN-SUFFIX,box.com,布吉岛
  - DOMAIN-SUFFIX,box.net,布吉岛
  - DOMAIN-SUFFIX,cachefly.net,布吉岛
  - DOMAIN-SUFFIX,chromium.org,布吉岛
  - DOMAIN-SUFFIX,cl.ly,布吉岛
  - DOMAIN-SUFFIX,cloudflare.com,布吉岛
  - DOMAIN-SUFFIX,cloudfront.net,布吉岛
  - DOMAIN-SUFFIX,cloudmagic.com,布吉岛
  - DOMAIN-SUFFIX,cmail19.com,布吉岛
  - DOMAIN-SUFFIX,cnet.com,布吉岛
  - DOMAIN-SUFFIX,cocoapods.org,布吉岛
  - DOMAIN-SUFFIX,comodoca.com,布吉岛
  - DOMAIN-SUFFIX,crashlytics.com,布吉岛
  - DOMAIN-SUFFIX,culturedcode.com,布吉岛
  - DOMAIN-SUFFIX,d.pr,布吉岛
  - DOMAIN-SUFFIX,danilo.to,布吉岛
  - DOMAIN-SUFFIX,dayone.me,布吉岛
  - DOMAIN-SUFFIX,db.tt,布吉岛
  - DOMAIN-SUFFIX,deskconnect.com,布吉岛
  - DOMAIN-SUFFIX,disq.us,布吉岛
  - DOMAIN-SUFFIX,disqus.com,布吉岛
  - DOMAIN-SUFFIX,disquscdn.com,布吉岛
  - DOMAIN-SUFFIX,dnsimple.com,布吉岛
  - DOMAIN-SUFFIX,docker.com,布吉岛
  - DOMAIN-SUFFIX,dribbble.com,布吉岛
  - DOMAIN-SUFFIX,droplr.com,布吉岛
  - DOMAIN-SUFFIX,duckduckgo.com,布吉岛
  - DOMAIN-SUFFIX,dueapp.com,布吉岛
  - DOMAIN-SUFFIX,dytt8.net,布吉岛
  - DOMAIN-SUFFIX,edgecastcdn.net,布吉岛
  - DOMAIN-SUFFIX,edgekey.net,布吉岛
  - DOMAIN-SUFFIX,edgesuite.net,布吉岛
  - DOMAIN-SUFFIX,engadget.com,布吉岛
  - DOMAIN-SUFFIX,entrust.net,布吉岛
  - DOMAIN-SUFFIX,eurekavpt.com,布吉岛
  - DOMAIN-SUFFIX,evernote.com,布吉岛
  - DOMAIN-SUFFIX,fabric.io,布吉岛
  - DOMAIN-SUFFIX,fast.com,布吉岛
  - DOMAIN-SUFFIX,fastly.net,布吉岛
  - DOMAIN-SUFFIX,fc2.com,布吉岛
  - DOMAIN-SUFFIX,feedburner.com,布吉岛
  - DOMAIN-SUFFIX,feedly.com,布吉岛
  - DOMAIN-SUFFIX,feedsportal.com,布吉岛
  - DOMAIN-SUFFIX,fiftythree.com,布吉岛
  - DOMAIN-SUFFIX,firebaseio.com,布吉岛
  - DOMAIN-SUFFIX,flexibits.com,布吉岛
  - DOMAIN-SUFFIX,flickr.com,布吉岛
  - DOMAIN-SUFFIX,flipboard.com,布吉岛
  - DOMAIN-SUFFIX,g.co,布吉岛
  - DOMAIN-SUFFIX,gabia.net,布吉岛
  - DOMAIN-SUFFIX,geni.us,布吉岛
  - DOMAIN-SUFFIX,gfx.ms,布吉岛
  - DOMAIN-SUFFIX,ggpht.com,布吉岛
  - DOMAIN-SUFFIX,ghostnoteapp.com,布吉岛
  - DOMAIN-SUFFIX,git.io,布吉岛
  - DOMAIN-KEYWORD,github,布吉岛
  - DOMAIN-SUFFIX,globalsign.com,布吉岛
  - DOMAIN-SUFFIX,gmodules.com,布吉岛
  - DOMAIN-SUFFIX,godaddy.com,布吉岛
  - DOMAIN-SUFFIX,golang.org,布吉岛
  - DOMAIN-SUFFIX,gongm.in,布吉岛
  - DOMAIN-SUFFIX,goo.gl,布吉岛
  - DOMAIN-SUFFIX,goodreaders.com,布吉岛
  - DOMAIN-SUFFIX,goodreads.com,布吉岛
  - DOMAIN-SUFFIX,gravatar.com,布吉岛
  - DOMAIN-SUFFIX,gstatic.com,布吉岛
  - DOMAIN-SUFFIX,gvt0.com,布吉岛
  - DOMAIN-SUFFIX,hockeyapp.net,布吉岛
  - DOMAIN-SUFFIX,hotmail.com,布吉岛
  - DOMAIN-SUFFIX,icons8.com,布吉岛
  - DOMAIN-SUFFIX,ifixit.com,布吉岛
  - DOMAIN-SUFFIX,ift.tt,布吉岛
  - DOMAIN-SUFFIX,ifttt.com,布吉岛
  - DOMAIN-SUFFIX,iherb.com,布吉岛
  - DOMAIN-SUFFIX,imageshack.us,布吉岛
  - DOMAIN-SUFFIX,img.ly,布吉岛
  - DOMAIN-SUFFIX,imgur.com,布吉岛
  - DOMAIN-SUFFIX,imore.com,布吉岛
  - DOMAIN-SUFFIX,instapaper.com,布吉岛
  - DOMAIN-SUFFIX,ipn.li,布吉岛
  - DOMAIN-SUFFIX,is.gd,布吉岛
  - DOMAIN-SUFFIX,issuu.com,布吉岛
  - DOMAIN-SUFFIX,itgonglun.com,布吉岛
  - DOMAIN-SUFFIX,itun.es,布吉岛
  - DOMAIN-SUFFIX,ixquick.com,布吉岛
  - DOMAIN-SUFFIX,j.mp,布吉岛
  - DOMAIN-SUFFIX,js.revsci.net,布吉岛
  - DOMAIN-SUFFIX,jshint.com,布吉岛
  - DOMAIN-SUFFIX,jtvnw.net,布吉岛
  - DOMAIN-SUFFIX,justgetflux.com,布吉岛
  - DOMAIN-SUFFIX,kat.cr,布吉岛
  - DOMAIN-SUFFIX,klip.me,布吉岛
  - DOMAIN-SUFFIX,libsyn.com,布吉岛
  - DOMAIN-SUFFIX,linkedin.com,布吉岛
  - DOMAIN-SUFFIX,line-apps.com,布吉岛
  - DOMAIN-SUFFIX,linode.com,布吉岛
  - DOMAIN-SUFFIX,lithium.com,布吉岛
  - DOMAIN-SUFFIX,littlehj.com,布吉岛
  - DOMAIN-SUFFIX,live.com,布吉岛
  - DOMAIN-SUFFIX,live.net,布吉岛
  - DOMAIN-SUFFIX,livefilestore.com,布吉岛
  - DOMAIN-SUFFIX,llnwd.net,布吉岛
  - DOMAIN-SUFFIX,macid.co,布吉岛
  - DOMAIN-SUFFIX,macromedia.com,布吉岛
  - DOMAIN-SUFFIX,macrumors.com,布吉岛
  - DOMAIN-SUFFIX,mashable.com,布吉岛
  - DOMAIN-SUFFIX,mathjax.org,布吉岛
  - DOMAIN-SUFFIX,medium.com,布吉岛
  - DOMAIN-SUFFIX,mega.co.nz,布吉岛
  - DOMAIN-SUFFIX,mega.nz,布吉岛
  - DOMAIN-SUFFIX,megaupload.com,布吉岛
  - DOMAIN-SUFFIX,microsofttranslator.com,布吉岛
  - DOMAIN-SUFFIX,mindnode.com,布吉岛
  - DOMAIN-SUFFIX,mobile01.com,布吉岛
  - DOMAIN-SUFFIX,modmyi.com,布吉岛
  - DOMAIN-SUFFIX,msedge.net,布吉岛
  - DOMAIN-SUFFIX,myfontastic.com,布吉岛
  - DOMAIN-SUFFIX,name.com,布吉岛
  - DOMAIN-SUFFIX,nextmedia.com,布吉岛
  - DOMAIN-SUFFIX,nsstatic.net,布吉岛
  - DOMAIN-SUFFIX,nssurge.com,布吉岛
  - DOMAIN-SUFFIX,nyt.com,布吉岛
  - DOMAIN-SUFFIX,nytimes.com,布吉岛
  - DOMAIN-SUFFIX,omnigroup.com,布吉岛
  - DOMAIN-SUFFIX,onedrive.com,布吉岛
  - DOMAIN-SUFFIX,onenote.com,布吉岛
  - DOMAIN-SUFFIX,ooyala.com,布吉岛
  - DOMAIN-SUFFIX,openvpn.net,布吉岛
  - DOMAIN-SUFFIX,openwrt.org,布吉岛
  - DOMAIN-SUFFIX,orkut.com,布吉岛
  - DOMAIN-SUFFIX,osxdaily.com,布吉岛
  - DOMAIN-SUFFIX,outlook.com,布吉岛
  - DOMAIN-SUFFIX,ow.ly,布吉岛
  - DOMAIN-SUFFIX,paddleapi.com,布吉岛
  - DOMAIN-SUFFIX,parallels.com,布吉岛
  - DOMAIN-SUFFIX,parse.com,布吉岛
  - DOMAIN-SUFFIX,pdfexpert.com,布吉岛
  - DOMAIN-SUFFIX,periscope.tv,布吉岛
  - DOMAIN-SUFFIX,pinboard.in,布吉岛
  - DOMAIN-SUFFIX,pinterest.com,布吉岛
  - DOMAIN-SUFFIX,pixelmator.com,布吉岛
  - DOMAIN-SUFFIX,pixiv.net,布吉岛
  - DOMAIN-SUFFIX,playpcesor.com,布吉岛
  - DOMAIN-SUFFIX,playstation.com,布吉岛
  - DOMAIN-SUFFIX,playstation.com.hk,布吉岛
  - DOMAIN-SUFFIX,playstation.net,布吉岛
  - DOMAIN-SUFFIX,playstationnetwork.com,布吉岛
  - DOMAIN-SUFFIX,pushwoosh.com,布吉岛
  - DOMAIN-SUFFIX,rime.im,布吉岛
  - DOMAIN-SUFFIX,servebom.com,布吉岛
  - DOMAIN-SUFFIX,sfx.ms,布吉岛
  - DOMAIN-SUFFIX,shadowsocks.org,布吉岛
  - DOMAIN-SUFFIX,sharethis.com,布吉岛
  - DOMAIN-SUFFIX,shazam.com,布吉岛
  - DOMAIN-SUFFIX,skype.com,布吉岛
  - DOMAIN-SUFFIX,smartdns布吉岛.com,布吉岛
  - DOMAIN-SUFFIX,smartmailcloud.com,布吉岛
  - DOMAIN-SUFFIX,sndcdn.com,布吉岛
  - DOMAIN-SUFFIX,sony.com,布吉岛
  - DOMAIN-SUFFIX,soundcloud.com,布吉岛
  - DOMAIN-SUFFIX,sourceforge.net,布吉岛
  - DOMAIN-SUFFIX,spotify.com,布吉岛
  - DOMAIN-SUFFIX,squarespace.com,布吉岛
  - DOMAIN-SUFFIX,sstatic.net,布吉岛
  - DOMAIN-SUFFIX,st.luluku.pw,布吉岛
  - DOMAIN-SUFFIX,stackoverflow.com,布吉岛
  - DOMAIN-SUFFIX,startpage.com,布吉岛
  - DOMAIN-SUFFIX,staticflickr.com,布吉岛
  - DOMAIN-SUFFIX,steamcommunity.com,布吉岛
  - DOMAIN-SUFFIX,symauth.com,布吉岛
  - DOMAIN-SUFFIX,symcb.com,布吉岛
  - DOMAIN-SUFFIX,symcd.com,布吉岛
  - DOMAIN-SUFFIX,tapbots.com,布吉岛
  - DOMAIN-SUFFIX,tapbots.net,布吉岛
  - DOMAIN-SUFFIX,tdesktop.com,布吉岛
  - DOMAIN-SUFFIX,techcrunch.com,布吉岛
  - DOMAIN-SUFFIX,techsmith.com,布吉岛
  - DOMAIN-SUFFIX,thepiratebay.org,布吉岛
  - DOMAIN-SUFFIX,theverge.com,布吉岛
  - DOMAIN-SUFFIX,time.com,布吉岛
  - DOMAIN-SUFFIX,timeinc.net,布吉岛
  - DOMAIN-SUFFIX,tiny.cc,布吉岛
  - DOMAIN-SUFFIX,tinypic.com,布吉岛
  - DOMAIN-SUFFIX,tmblr.co,布吉岛
  - DOMAIN-SUFFIX,todoist.com,布吉岛
  - DOMAIN-SUFFIX,trello.com,布吉岛
  - DOMAIN-SUFFIX,trustasiassl.com,布吉岛
  - DOMAIN-SUFFIX,tumblr.co,布吉岛
  - DOMAIN-SUFFIX,tumblr.com,布吉岛
  - DOMAIN-SUFFIX,tweetdeck.com,布吉岛
  - DOMAIN-SUFFIX,tweetmarker.net,布吉岛
  - DOMAIN-SUFFIX,twitch.tv,布吉岛
  - DOMAIN-SUFFIX,txmblr.com,布吉岛
  - DOMAIN-SUFFIX,typekit.net,布吉岛
  - DOMAIN-SUFFIX,ubertags.com,布吉岛
  - DOMAIN-SUFFIX,ublock.org,布吉岛
  - DOMAIN-SUFFIX,ubnt.com,布吉岛
  - DOMAIN-SUFFIX,ulyssesapp.com,布吉岛
  - DOMAIN-SUFFIX,urchin.com,布吉岛
  - DOMAIN-SUFFIX,usertrust.com,布吉岛
  - DOMAIN-SUFFIX,v.gd,布吉岛
  - DOMAIN-SUFFIX,v2ex.com,布吉岛
  - DOMAIN-SUFFIX,vimeo.com,布吉岛
  - DOMAIN-SUFFIX,vimeocdn.com,布吉岛
  - DOMAIN-SUFFIX,vine.co,布吉岛
  - DOMAIN-SUFFIX,vivaldi.com,布吉岛
  - DOMAIN-SUFFIX,vox-cdn.com,布吉岛
  - DOMAIN-SUFFIX,vsco.co,布吉岛
  - DOMAIN-SUFFIX,vultr.com,布吉岛
  - DOMAIN-SUFFIX,w.org,布吉岛
  - DOMAIN-SUFFIX,w3schools.com,布吉岛
  - DOMAIN-SUFFIX,webtype.com,布吉岛
  - DOMAIN-SUFFIX,wikiwand.com,布吉岛
  - DOMAIN-SUFFIX,wikileaks.org,布吉岛
  - DOMAIN-SUFFIX,wikimedia.org,布吉岛
  - DOMAIN-SUFFIX,wikipedia.com,布吉岛
  - DOMAIN-SUFFIX,wikipedia.org,布吉岛
  - DOMAIN-SUFFIX,windows.com,布吉岛
  - DOMAIN-SUFFIX,windows.net,布吉岛
  - DOMAIN-SUFFIX,wire.com,布吉岛
  - DOMAIN-SUFFIX,wordpress.com,布吉岛
  - DOMAIN-SUFFIX,workflowy.com,布吉岛
  - DOMAIN-SUFFIX,wp.com,布吉岛
  - DOMAIN-SUFFIX,wsj.com,布吉岛
  - DOMAIN-SUFFIX,wsj.net,布吉岛
  - DOMAIN-SUFFIX,xda-developers.com,布吉岛
  - DOMAIN-SUFFIX,xeeno.com,布吉岛
  - DOMAIN-SUFFIX,xiti.com,布吉岛
  - DOMAIN-SUFFIX,yahoo.com,布吉岛
  - DOMAIN-SUFFIX,yimg.com,布吉岛
  - DOMAIN-SUFFIX,ying.com,布吉岛
  - DOMAIN-SUFFIX,yoyo.org,布吉岛
  - DOMAIN-SUFFIX,ytimg.com,布吉岛
  - DOMAIN-SUFFIX,telegra.ph,布吉岛
  - DOMAIN-SUFFIX,telegram.org,布吉岛
  - IP-CIDR,91.108.4.0/22,布吉岛,no-resolve
  - IP-CIDR,91.108.8.0/21,布吉岛,no-resolve
  - IP-CIDR,91.108.16.0/22,布吉岛,no-resolve
  - IP-CIDR,91.108.56.0/22,布吉岛,no-resolve
  - IP-CIDR,149.154.160.0/20,布吉岛,no-resolve
  - IP-CIDR6,2001:67c:4e8::/48,布吉岛,no-resolve
  - IP-CIDR6,2001:b28:f23d::/48,布吉岛,no-resolve
  - IP-CIDR6,2001:b28:f23f::/48,布吉岛,no-resolve
  - IP-CIDR,120.232.181.162/32,布吉岛,no-resolve
  - IP-CIDR,120.241.147.226/32,布吉岛,no-resolve
  - IP-CIDR,120.253.253.226/32,布吉岛,no-resolve
  - IP-CIDR,120.253.255.162/32,布吉岛,no-resolve
  - IP-CIDR,120.253.255.34/32,布吉岛,no-resolve
  - IP-CIDR,120.253.255.98/32,布吉岛,no-resolve
  - IP-CIDR,180.163.150.162/32,布吉岛,no-resolve
  - IP-CIDR,180.163.150.34/32,布吉岛,no-resolve
  - IP-CIDR,180.163.151.162/32,布吉岛,no-resolve
  - IP-CIDR,180.163.151.34/32,布吉岛,no-resolve
  - IP-CIDR,203.208.39.0/24,布吉岛,no-resolve
  - IP-CIDR,203.208.40.0/24,布吉岛,no-resolve
  - IP-CIDR,203.208.41.0/24,布吉岛,no-resolve
  - IP-CIDR,203.208.43.0/24,布吉岛,no-resolve
  - IP-CIDR,203.208.50.0/24,布吉岛,no-resolve
  - IP-CIDR,220.181.174.162/32,布吉岛,no-resolve
  - IP-CIDR,220.181.174.226/32,布吉岛,no-resolve
  - IP-CIDR,220.181.174.34/32,布吉岛,no-resolve
  - DOMAIN,injections.adguard.org,DIRECT
  - DOMAIN,local.adguard.org,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-KEYWORD,-cn,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,布吉岛
